project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - mods.qmd

website:
  title: "Football DNA"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: mods.qmd
        text: "Game Totals & Spreads"
      - href: fantasy.qmd
        text: "Fantasy Football"

format:
  html:
    theme: cosmo